### PR TITLE
Enable dependabot security auto-pr

### PR DESCRIPTION
**Pull request by AndrejMitrovic**
There has been a security notification about a vulnerability in one of our dependencies since August: https://github.com/bpfkorea/boa-sdk-ts/network/alerts

Trying to see if this can help us stay up to date.

I've used the guide here:

https://dependabot.com/docs/config-file/#dependabot-config-files
https://github.com/dependabot/preview-demo/blob/main/.dependabot/config.yml

### CODE REVIEW

**Comment by TrustHenry** [comment]
https://github.com/bpfkorea/stoa/commit/291e46877dc2ca3be16645a3b7cd84d94e5cc979
Stoa doesn't have .dependabot/config.yml How did it work?

**Review by TrustHenry — APPROVED** [review]
I hope it works well.

**Comment by AndrejMitrovic** [comment]
Maybe there's a config option in the repository. I'm not sure..

**Comment by AndrejMitrovic** [comment]
Screen Shot 2020-11-13 at 16 28 47

I think that last option should have made PRs automatically. Unless I'm misunderstanding what it says.

**Comment by Geod24** [comment]
It's automatic. I've seen the notification, but for some reason dependabot doesn't seem  to be able to create the PR. Looks like a bug on GH side. In any case, I doubt this PR is needed to get dependabot. I  think we should just do this update manually to unstuck it.

**Comment by AndrejMitrovic** [comment]
> Looks like a bug on GH side. 

Yep that's what I was afraid of.

I was hoping it would at least get us notified, maybe via e-mail?

**Pull request closed without merging**
